export enum KeyEnum {
  PORT = 'PORT',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
}
